name: Build Image using Containerfile
on: [push]

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ptr-test
  IMAGE_TAGS: v1 ${{ github.sha }}
  

jobs:
  login:
      name: Log in to GitHub Container Registry
      runs-on: ubuntu-20.04
      permissions:
        contents: read
        packages: write
      steps:
        - name: lowercase registry
          run: |
            echo "IMAGE_REGISTRY_LC=${IMAGE_REGISTRY,,}" >>${GITHUB_ENV}
        
        - name: Log in to ghcr.io
          uses: redhat-actions/podman-login@v1
          with:
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            registry: ${{ env.IMAGE_REGISTRY_LC }}
  
        - uses: actions/checkout@v4
  
        - name: Buildah Action
          uses: redhat-actions/buildah-build@v2
          id: build_image
          with:
            image: my-new-image
            tags: v1 ${{ github.sha }}
            containerfiles: example.containerfile

          # Checkout push-to-registry action github repository
        - name: Checkout Push to Registry action
          uses: actions/checkout@v4
    
        - name: Install latest podman
          if: matrix.install_latest
          run: |
              bash .github/install_latest_podman.sh
    
         
          # Push the image to GHCR (Image Registry)
        - name: Push To GHCR
          uses: redhat-actions/push-to-registry@v2
          id: push
          with:
              image: ${{ steps.build_image.outputs.image }}
              tags: ${{ steps.build_image.outputs.tags }}
              registry: ${{ env.IMAGE_REGISTRY_LC }}
              username: ${{ env.REGISTRY_USER }}
              password: ${{ env.REGISTRY_PASSWORD }}
              extra-args: |
                --disable-content-trust
    
        - name: Echo outputs
          run: |
              echo "${{ toJSON(steps.push.outputs) }}"
        - name: Run image
          run: docker run ghcr.io/plukewang/my-new-image:acc64d5364c0cb2aed655602613fab3c70682bc5 -v ${{github.workspace}}:/workspace -w /workspace build.bash 
